/* ============================================================
   EXPERIMENTS: the single source of truth.
   Append an object to add an experiment. Cards, filters, counts,
   the hero console, detail pages and related links all generate
   from this array.

   type:      "tool" | "insight" | "evaluation"
   status:    optional. Only set when it tells the visitor something.
   visual:    which illustration to draw (see ILLUSTRATIONS).
   question:  optional. Featured in the hero "Ask the lab" console.
   hypothesis: completes the sentence "We wanted to explore whether…"
   REVIEW:    hypothesis, approach and next are written from the
              source descriptions; confirm them before publishing.
   ============================================================ */
const TYPES = {
  tool:       { label: "Tool",       plural: "Tools",       desc: "Things we built" },
  insight:    { label: "Insight",    plural: "Insights",    desc: "What practice taught us" },
  evaluation: { label: "Evaluation", plural: "Evaluations", desc: "Things we measured" }
};
const THEMES = {
  judgement: "Human judgement", research: "Research", "design-systems": "Design systems",
  engineering: "Engineering", automation: "Automation", prototyping: "Prototyping",
  knowledge: "Knowledge management", measurement: "Measuring impact", simulation: "Simulation",
  healthcare: "Healthcare", accessibility: "Accessibility"
};

const EXPERIMENTS = [
{ n:1, slug:"right-sizing-the-model", title:"Right-sizing the model", type:"tool", visual:"components", feature:true,
  question:"Does a bigger model build a better design system?",
  summary:"We rebuilt a legacy component library into a new design system. An oversized model kept improvising, so we swapped it for a smaller one paired with manual checks.",
  stats:[["~54%","of the rebuild completed by AI"],["~6 weeks","of effort saved"]],
  themes:["design-systems","judgement"], tools:[],
  hypothesis:"a smaller, more constrained model paired with human review would follow an existing system more faithfully than the most capable model available",
  approach:"The legacy library was migrated component by component. When the larger model began improvising beyond the system's rules, we switched to a smaller model and added manual checkpoints at each stage.",
  learned:["The most powerful model isn't always the right one. On a rule-bound task, the larger model's tendency to improvise worked against us.","A smaller model plus human checks delivered the rebuild, with more than half of the work completed by AI."],
  next:"Apply the same model-sizing judgement to other system-level migrations.", related:[2,11,4] },
{ n:2, slug:"the-redwood-icon-failure", title:"The Redwood icon failure", type:"insight", visual:"icons",
  summary:"On an earlier project, an oversized model kept replacing icons with literal text symbols, even after repeated instructions not to.",
  themes:["design-systems","judgement"], tools:[],
  hypothesis:"clear, repeated instructions would be enough to keep a large model from substituting icons",
  approach:"The model was asked to work within an existing icon set and was corrected each time it swapped an icon for a text symbol.",
  learned:["Repetition didn't fix it. The substitutions continued despite explicit instructions.","This failure directly shaped the model-sizing decision behind Right-sizing the model."],
  next:"Read alongside Right-sizing the model as one before-and-after story.", related:[1,23] },
{ n:3, slug:"when-not-to-let-ai-synthesise", title:"When not to let AI synthesise", type:"insight", visual:"synthesis", feature:true,
  question:"Should AI synthesise your user interviews?",
  summary:"Handing nine user interviews to Claude for synthesis risked compounding gaps rather than closing them. A manual rewatch surfaced three findings the synthesis missed.",
  stats:[["9","user interviews"],["3","findings the AI synthesis missed"]],
  themes:["research","judgement"], tools:["Claude"],
  hypothesis:"Claude could synthesise a full round of interviews reliably enough to replace a manual pass",
  approach:"The interviews were synthesised with Claude, then rewatched independently and compared against the AI output.",
  learned:["Automated synthesis can compound gaps in research instead of closing them.","A manual rewatch caught three findings the synthesis had missed.","Human review remained essential to the quality of the findings."],
  next:"Define where AI synthesis fits in our research workflow, and where a human pass is non-negotiable.", related:[7,14,21] },
{ n:4, slug:"component-to-instant-documentation", title:"Turning a component into instant documentation", type:"tool", visual:"componentDoc",
  summary:"A Figma plugin that automatically documents a component's variants, anatomy, colours and tokens.",
  themes:["design-systems","automation"], tools:["Figma"],
  hypothesis:"documentation could be generated directly from the component itself, removing a slow manual step",
  approach:"The plugin reads a selected component in Figma and produces structured documentation of its variants, anatomy, colours and tokens.",
  learned:["Documentation that used to take manual effort can come straight from the source component.","Small, everyday tools remove real friction from design system work."],
  next:"Extend the plugin to more component types and connect its output to our documentation.", related:[24,11,1] },
{ n:5, slug:"tool-chain-for-a-legacy-codebase", title:"A tool chain for a legacy codebase", type:"tool", visual:"chain",
  question:"Can AI make sense of a legacy codebase?",
  summary:"Three chained tools for an older codebase: plain-English querying, ticket-to-estimate, and automated test generation.",
  stats:[["3","chained tools"],["~99%","reliability, given a well-written ticket"]],
  themes:["engineering","automation"], tools:[],
  hypothesis:"a chain of focused AI tools could make an unfamiliar legacy codebase faster to understand, estimate and test",
  approach:"Each tool does one job: answering plain-English questions about the code, turning tickets into estimates, and generating tests. The output of each step feeds the next.",
  learned:["Reliability reached around 99% when the input ticket was well written.","The quality of the input shaped the quality of every downstream step."],
  next:"Improve ticket-writing guidance so the chain performs consistently.", related:[13,20,17] },
{ n:6, slug:"what-converges-and-what-doesnt", title:"What converges, and what doesn't", type:"insight", visual:"converge",
  question:"Does sketching on paper still beat designing with AI?",
  summary:"A paper-first design process against a Claude-only one, judged blind. The AI-only work scored higher.",
  themes:["prototyping","judgement"], tools:["Claude"],
  hypothesis:"starting on paper would produce stronger design work than working with Claude alone",
  approach:"The same brief was tackled two ways, one starting from paper sketches and one using only Claude. The outputs were then judged blind.",
  learned:["In blind judging, the Claude-only work scored higher.","The result resists an easy headline: what converges between the two approaches matters as much as the score."],
  next:"Explore which parts of the process converge, and which still benefit from starting by hand.", related:[14,12,11] },
{ n:7, slug:"four-things-a-synthesis-pass-taught-us", title:"Four things a synthesis pass taught us", type:"insight", visual:"fourLessons",
  summary:"Four practical lessons from running an AI synthesis pass on real research.",
  themes:["research"], tools:[],
  hypothesis:"an AI synthesis pass could fit into everyday research work, provided we understood its limits",
  approach:"A synthesis pass was run on real research material, and its output was reviewed closely against the source.",
  learned:["Give it categories to work with.","Expect non-determinism.","Watch for misattribution.","It made one genuine catch, unprompted."],
  next:"Build these lessons into a shared synthesis checklist.", related:[3,9,14] },
{ n:8, slug:"natural-language-for-a-tedious-task", title:"Natural language for a tedious task", type:"tool", visual:"nlTask",
  summary:"A Jira worklog tool that runs entirely on plain-language prompts.",
  themes:["automation"], tools:["Jira"],
  hypothesis:"a repetitive admin task could be handled through conversation instead of forms",
  approach:"Instead of navigating forms, you describe the work in a sentence and the tool records the worklog entry.",
  learned:["Some of the most useful AI tools are deliberately unglamorous.","Removing small, repeated friction adds up across a team."],
  next:"Apply the same pattern to other repetitive admin tasks.", related:[22,17,19] },
{ n:9, slug:"distill", title:"Distill: turning calls into a searchable archive", short:"Distill", type:"tool", visual:"distill", status:"In development",
  summary:"A skill that automatically indexes Fathom and Zoom call transcripts into a searchable archive.",
  themes:["knowledge","automation","research"], tools:["Fathom","Zoom"],
  hypothesis:"call transcripts could become a searchable archive without anyone indexing them by hand",
  approach:"The skill picks up new transcripts from Fathom and Zoom and indexes them automatically.",
  learned:["Automatic indexing works, but the current version is too slow and too token-heavy.","Not every experiment is a finished win. This one is being rebuilt."],
  next:"Distill is being rebuilt to reduce processing time and token cost.", related:[24,19,10] },
{ n:10, slug:"sparr", title:"SPARR: rehearsing the hard conversation", short:"SPARR", type:"tool", visual:"sparr", status:"Tested", feature:true,
  question:"Can you rehearse a difficult conversation with AI?",
  summary:"SPARR simulates a stakeholder from their meeting history, so you can rehearse a difficult conversation before it happens.",
  stats:[["40–60%","accuracy, rated by people who know the real person"]],
  themes:["simulation","knowledge"], tools:[],
  hypothesis:"a person's meeting history holds enough signal to simulate them well enough to rehearse with",
  approach:"SPARR builds a simulated stakeholder from past meeting history. Testers who knew the real person held practice conversations and rated how accurate it felt.",
  learned:["Testers who knew the real person rated it 40–60% accurate.","The simulated tone came across as too aggressive.","Being candid about these limits is part of designing a tool like this responsibly."],
  next:"Refine tone calibration and test with a wider group.", related:[24,9,19] },
{ n:11, slug:"90-percent-consistent-wireframes", title:"90% consistent wireframes", type:"evaluation", visual:"wireframes", feature:true,
  question:"Can AI-generated wireframes stay on-system?",
  summary:"We converted a component kit to markdown, then generated wireframes against it.",
  stats:[["~9 in 10","wireframes stay consistent with the kit"]],
  themes:["design-systems","prototyping"], tools:["Markdown"],
  hypothesis:"describing a component kit in markdown would keep AI-generated wireframes consistent with the system",
  approach:"The kit was translated into a markdown description. Wireframes were generated against it and reviewed together as a set.",
  learned:["Wireframes held together roughly nine times in ten.","A structured description gives the model something concrete to stay faithful to."],
  next:"Study the one in ten that drift, and tighten the kit description.", related:[4,1,12] },
{ n:12, slug:"one-day-unfamiliar-domain", title:"One day, unfamiliar domain", type:"tool", visual:"oneDay",
  summary:"One day to demo three screens in an unfamiliar domain. It shipped fast, then kept growing for weeks after.",
  stats:[["1 day","to a three-screen demo"]],
  themes:["prototyping"], tools:[],
  hypothesis:"AI could help a designer reach a credible demo in an unfamiliar domain within a single day",
  approach:"Working to a one-day deadline, we used AI to get up to speed on the domain and produce three demo screens.",
  learned:["The one-day demo shipped on time.","It kept growing for weeks afterwards. A fast start became a lasting project."],
  next:"Capture the approach as a playbook for rapid domain ramp-ups.", related:[11,6] },
{ n:13, slug:"a-day-of-tests-instead-of-three", title:"A day of tests instead of three", type:"evaluation", visual:"tests",
  summary:"A full end-to-end test suite written in a day, instead of the usual two to three.",
  stats:[["1 day","instead of two to three"],["~70–90%","of effort saved"]],
  themes:["engineering"], tools:[],
  hypothesis:"AI could take on most of the effort of writing an end-to-end test suite",
  approach:"The suite was written with AI assistance in a single continuous working session, then compared against the usual effort.",
  learned:["Effort saved was roughly 70–90%.","It breaks down outside a single continuous chat thread, so keeping context intact matters."],
  next:"Find reliable ways to carry context across sessions.", related:[5,20] },
{ n:14, slug:"setup-is-the-work", title:"Setup is the work", type:"insight", visual:"setup", feature:true,
  question:"How much does context really change the output?",
  summary:"Same transcripts, same model, two outputs side by side: one from a vague one-line ask, one after 30 minutes of real context.",
  stats:[["30 min","of context-setting before the ask"]],
  themes:["judgement","research"], tools:[],
  hypothesis:"time spent setting up context changes the output more than the request itself",
  approach:"The same transcripts went to the same model twice: once with a one-line request, and once after 30 minutes of context-setting. The two outputs were compared side by side.",
  learned:["With the inputs and the model held constant, context made the difference.","Setting up the problem is the work, not a preamble to it."],
  next:"Turn effective context-setting into a repeatable team practice.", related:[16,3,6] },
{ n:15, slug:"metrics-that-lie", title:"Metrics that lie", type:"insight", visual:"metrics",
  question:"Are you measuring AI adoption, or AI impact?",
  summary:"Shipped-feature counts and token-usage leaderboards climb while real outcomes stay flat.",
  themes:["measurement","judgement"], tools:[],
  hypothesis:"the easiest AI metrics to count would track the outcomes that actually matter",
  approach:"Common AI productivity metrics were examined against real outcomes, drawing on three concrete examples.",
  learned:["Activity metrics like features shipped and tokens used can rise while outcomes don't move.","Measure outcomes, not activity."],
  next:"Define outcome-based measures for AI-assisted work.", related:[18,16] },
{ n:16, slug:"the-explanation-test", title:"The explanation test", type:"insight", visual:"explanation",
  summary:"Before any AI output ships, explain it out loud as if it were entirely your own work.",
  themes:["judgement"], tools:[],
  hypothesis:"saying an AI output aloud, as your own, would expose its weaknesses before it reached anyone else",
  approach:"Outputs are explained aloud before they ship, as though the author had produced every part of them.",
  learned:["A strategy that looked sound fell apart the moment it was said aloud.","If you can't explain it, you don't own it yet."],
  next:"Make the explanation test a standard review step.", related:[14,15,21] },
{ n:17, slug:"quietly-rewriting-the-record", title:"Quietly rewriting the record", type:"tool", visual:"rewrite",
  summary:"An automation that updates ticket links the moment a design is marked ready for development.",
  themes:["automation","engineering"], tools:[],
  hypothesis:"design-to-development handoff links could keep themselves up to date",
  approach:"When a design's status changes to ready for development, the automation updates the linked tickets with no manual step.",
  learned:["It removes a manual step from every handoff.","It raises an open accountability question: who is responsible when the record changes itself?"],
  next:"Resolve the accountability model before a wider rollout.", related:[18,20,8] },
{ n:18, slug:"the-dashboard-nobody-was-sure-was-useful", title:"The dashboard nobody was sure was useful", type:"insight", visual:"dashboard",
  summary:"A daily Slack digest summarising design and code activity, and an honest debate about its value.",
  themes:["automation","measurement"], tools:["Slack"],
  hypothesis:"a daily activity digest would help the team understand what was happening across design and code",
  approach:"Activity across design and code was summarised into a single daily Slack message.",
  learned:["It prompted genuine debate about whether it tells you anything useful at all.","Visibility is not the same as insight."],
  next:"Test which signals the team would actually act on.", related:[15,17,22] },
{ n:19, slug:"a-solo-designers-memory-externalised", title:"A solo designer's memory, externalised", type:"tool", visual:"memory",
  summary:"Meeting transcripts become a living project file: context, decisions and handoff briefs on request.",
  themes:["knowledge"], tools:[],
  hypothesis:"meeting transcripts could keep a project's context and decisions alive for a designer working alone",
  approach:"Transcripts feed a single project file that captures context and decisions, and produces handoff briefs when asked.",
  learned:["It gives an undocumented project a memory.","It breaks as soon as two people edit it at once."],
  next:"Explore support for multiple collaborators.", related:[9,24,10] },
{ n:20, slug:"telling-developers-what-theyre-missing", title:"Telling developers what they don't know they're missing", type:"tool", visual:"prbot",
  summary:"A pull-request bot that comments with the exact commands needed to see a teammate's backend changes.",
  themes:["engineering","automation"], tools:[],
  hypothesis:"a bot could close the gap between a backend change and a teammate seeing it running",
  approach:"When a pull request includes backend changes, the bot posts the commands needed to run them.",
  learned:["Surfacing the next step at the right moment removes guesswork for developers."],
  next:"Extend the bot to other kinds of change.", related:[5,13,17] },
{ n:21, slug:"what-ai-cant-access-about-a-person", title:"What AI can't access about a person", type:"insight", visual:"cantAccess", feature:true,
  question:"What can't AI know about a person?",
  summary:"AI can describe a tired nurse in full detail. It can't hear the specific way she says a bad situation is \u201cnormal now, I'm used to it.\u201d",
  themes:["research","healthcare","judgement"], tools:[],
  hypothesis:"there are dimensions of human research that an AI description cannot reach",
  approach:"We contrasted an AI-generated description of a nurse with what emerges when you actually listen to one.",
  learned:["What matters most can live in how something is said, not what is said.","In healthcare research, listening to real people remains irreplaceable."],
  next:"Design research workflows that protect time for direct listening.", related:[3,16,14] },
{ n:22, slug:"one-inbox-to-route-everything-through", title:"One inbox to route everything through", type:"tool", visual:"inbox",
  summary:"Forwarding rules consolidate email, Slack and Teams into one inbox. Every two hours, a script feeds Claude, which produces an action digest.",
  stats:[["3","channels in one inbox"],["2 hours","between action digests"]],
  themes:["automation"], tools:["Claude","Slack","Teams"],
  hypothesis:"routing every channel into one place would let AI produce a single, reliable list of actions",
  approach:"Forwarding rules gather messages from each channel. A scheduled script passes them to Claude every two hours to produce an action digest.",
  learned:["One consolidated view is what makes a single digest possible.","Client tooling constraints shape what can be connected."],
  next:"Validate the approach against different client tooling setups.", related:[8,18,19] },
{ n:23, slug:"a-design-critic-still-learning-to-see", title:"A design critic that's still learning to see", type:"tool", visual:"critic", status:"Early prototype",
  summary:"An automated heuristics and accessibility review for Figma designs.",
  themes:["accessibility","design-systems"], tools:["Figma"],
  hypothesis:"an automated pass could catch heuristic and accessibility issues before a design review",
  approach:"The tool checks a Figma design against usability heuristics and accessibility guidelines and flags what it finds.",
  learned:["It reliably flags the obvious issues.","It misses the specific, contextual ones, which still need a designer's eye."],
  next:"Teach it to recognise context-specific issues.", related:[4,11,2] },
{ n:24, slug:"ditto", title:"Ditto", type:"tool", visual:"ditto", status:"Launching soon",
  summary:"A shared design-reference plugin for Figma.",
  themes:["design-systems","knowledge"], tools:["Figma"],
  hypothesis:"a shared plugin could give the whole team one place for design references",
  approach:"Ditto went through two backend migrations on the way to a stable foundation.",
  learned:["The backend was migrated twice to get the foundation right."],
  next:"Ditto is being prepared for publication to the Figma Community.", related:[9,10,4] }
];
